config/routes.rb
Rails.application.routes.draw do
  resources :meals
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/meal.rb
class Meal < ApplicationRecord
  mount_uploader :picture, PictureUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/meals_controller.rb
class MealsController < ApplicationController
  before_action :set_meal, only: [:show, :edit, :update, :destroy]

  # GET /meals
  # GET /meals.json
  def index
    @meals = Meal.all
  end

  # GET /meals/1
  # GET /meals/1.json
  def show
  end

  # GET /meals/new
  def new
    @meal = Meal.new
  end

  # GET /meals/1/edit
  def edit
  end

  # POST /meals
  # POST /meals.json
  def create
    @meal = Meal.new(meal_params)

    respond_to do |format|
      if @meal.save
        format.html { redirect_to @meal, notice: 'Meal was successfully created.' }
        format.json { render :show, status: :created, location: @meal }
      else
        format.html { render :new }
        format.json { render json: @meal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /meals/1
  # PATCH/PUT /meals/1.json
  def update
    respond_to do |format|
      if @meal.update(meal_params)
        format.html { redirect_to @meal, notice: 'Meal was successfully updated.' }
        format.json { render :show, status: :ok, location: @meal }
      else
        format.html { render :edit }
        format.json { render json: @meal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meals/1
  # DELETE /meals/1.json
  def destroy
    @meal.destroy
    respond_to do |format|
      format.html { redirect_to meals_url, notice: 'Meal was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_meal
      @meal = Meal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def meal_params
      params.require(:meal).permit(:title, :date_eaten, :meal_type, :calories, :notes, :picture)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meals_helper.rb
module MealsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MealTracker</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/meals/_form.html.erb
<%= form_with(model: meal, local: true) do |form| %>
  <% if meal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(meal.errors.count, "error") %> prohibited this meal from being saved:</h2>

      <ul>
      <% meal.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

 
  
  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :meal_title %>
  </div>

  <div class="field">
    <%= form.label :date_eaten %>
    <%= form.date_select :date_eaten, id: :meal_date_eaten %>
  </div>

  <div class="field">
    <%= form.label :meal_type %>
    <%= form.number_field :meal_type, id: :meal_meal_type %>
  </div>

  <div class="field">
    <%= form.label :calories %>
    <%= form.number_field :calories, id: :meal_calories %>
  </div>

  <div class="field">
    <%= form.label :notes %>
    <%= form.text_area :notes, id: :meal_notes %>
  </div>

  <div class="field">
    <%= form.label :picture %>
    <%= form.file_field :picture, id: :meal_picture %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/meals/edit.html.erb
<h1>Editing Meal</h1>

<%= render 'form', meal: @meal %>

<%= link_to 'Show', @meal %> |
<%= link_to 'Back', meals_path %>

app/views/meals/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Meals</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Date eaten</th>
      <th>Meal type</th>
      <th>Calories</th>
      <th>Notes</th>
      <th>Picture</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @meals.each do |meal| %>
      <tr>
        <td><%= meal.title %></td>
        <td><%= meal.date_eaten %></td>
        <td><%= meal.meal_type %></td>
        <td><%= meal.calories %></td>
        <td><%= meal.notes %></td>
        <td><%= meal.picture %></td>
        <td><%= link_to 'Show', meal %></td>
        <td><%= link_to 'Edit', edit_meal_path(meal) %></td>
        <td><%= link_to 'Destroy', meal, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Meal', new_meal_path %>

app/views/meals/new.html.erb
<h1>New Meal</h1>

<%= render 'form', meal: @meal %>

<%= link_to 'Back', meals_path %>

app/views/meals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @meal.title %>
</p>

<p>
  <strong>Date eaten:</strong>
  <%= @meal.date_eaten %>
</p>

<p>
  <strong>Meal type:</strong>
  <%= @meal.meal_type %>
</p>

<p>
  <strong>Calories:</strong>
  <%= @meal.calories %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @meal.notes %>
</p>

<p>
  <strong>Picture:</strong>
  <%= image_tag(@meal.picture_url, width: 70) if @meal.picture.present? %>
</p>

<%= link_to 'Edit', edit_meal_path(@meal) %> |
<%= link_to 'Back', meals_path %>